// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_VehicleCommSimulation();
Q_GHS_KEEP_REFERENCE(qml_register_types_VehicleCommSimulation)

class VehicleCommSimulationPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    VehicleCommSimulationPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_VehicleCommSimulation;
        Q_UNUSED(registration)
    }
};



#include "VehicleCommSimulationplugin_VehicleCommSimulationPlugin.moc"
